from __future__ import annotations

"""Verified opportunity seed catalog for Baghdad/Iraq youth."""

SEED_OPPORTUNITIES: list[dict] = [
    # Developer
    {
        "title_en": "Junior Web Developer (Verified)",
        "title_ar": "مطور ويب مبتدئ (موثق)",
        "description_en": "Build landing pages with React for a registered tech SME. Mentorship included.",
        "description_ar": "بناء صفحات ويب باستخدام React لدى شركة تقنية مسجلة مع إرشاد.",
        "organization": "Baghdad Tech Coop",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "freeCodeCamp Web Development Path",
        "title_ar": "مسار تطوير الويب على freeCodeCamp",
        "description_en": "Free self-paced curriculum with certificates for HTML, JS, and APIs.",
        "description_ar": "منهج مجاني ذاتي مع شهادات في HTML وJS وواجهات البرمجة.",
        "organization": "freeCodeCamp",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.freecodecamp.org/",
    },
    {
        "title_en": "CS50 Introduction to Computer Science",
        "title_ar": "مقدمة في علوم الحاسوب CS50",
        "description_en": "Harvard's free CS intro covering algorithms and programming.",
        "description_ar": "مقدمة مجانية من هارفارد في الخوارزميات والبرمجة.",
        "organization": "Harvard / edX",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://cs50.harvard.edu/",
    },
    # Designer
    {
        "title_en": "Junior UI Designer",
        "title_ar": "مصمم واجهات مبتدئ",
        "description_en": "Design mobile screens for a licensed product studio. Portfolio review.",
        "description_ar": "تصميم واجهات جوال لدى استوديو منتجات مرخص. مراجعة محفظة أعمال.",
        "organization": "Studio Al-Nahr",
        "position": "designer",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "offline",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Google UX Design Certificate",
        "title_ar": "شهادة جوجل لتصميم تجربة المستخدم",
        "description_en": "Professional certificate covering UX research and Figma basics.",
        "description_ar": "شهادة مهنية تغطي بحث تجربة المستخدم وأساسيات Figma.",
        "organization": "Google",
        "position": "designer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://grow.google/uxdesign/",
    },
    # Marketing
    {
        "title_en": "Digital Marketing Assistant",
        "title_ar": "مساعد تسويق رقمي",
        "description_en": "Support social campaigns for a registered retail brand.",
        "description_ar": "دعم حملات التواصل لعلامة تجارية مسجلة.",
        "organization": "Al-Rasheed Retail",
        "position": "marketing",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Google Digital Marketing Course",
        "title_ar": "دورة التسويق الرقمي من جوجل",
        "description_en": "Learn SEO, ads, and analytics with a recognized certificate.",
        "description_ar": "تعلم تحسين محركات البحث والإعلانات والتحليلات مع شهادة معترف بها.",
        "organization": "Google",
        "position": "marketing",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://grow.google/digitalmarketing/",
    },
    # Data
    {
        "title_en": "Junior Data Analyst",
        "title_ar": "محلل بيانات مبتدئ",
        "description_en": "Clean spreadsheets and build dashboards for an NGO monitoring unit.",
        "description_ar": "تنظيف جداول وبناء لوحات بيانات لوحدة مراقبة في منظمة.",
        "organization": "Youth Data Lab",
        "position": "data",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Google Data Analytics Certificate",
        "title_ar": "شهادة جوجل لتحليل البيانات",
        "description_en": "Structured path into data analytics with portfolio projects.",
        "description_ar": "مسار منظم لتحليل البيانات مع مشاريع محفظة.",
        "organization": "Google",
        "position": "data",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://grow.google/dataanalytics/",
    },
    # Teacher
    {
        "title_en": "Online English Tutor",
        "title_ar": "مدرس لغة إنجليزية أونلاين",
        "description_en": "Teach teens via a licensed edtech platform. Weekly payouts.",
        "description_ar": "تعليم المراهقين عبر منصة تعليمية مرخصة. دفعات أسبوعية.",
        "organization": "LearnIraq",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Online",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Teaching Skills Mini-Course",
        "title_ar": "دورة مصغرة لمهارات التدريس",
        "description_en": "Free modules on lesson planning and classroom engagement.",
        "description_ar": "وحدات مجانية عن تخطيط الدروس وتفاعل الصف.",
        "organization": "Coursera",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/",
    },
    # Accountant
    {
        "title_en": "Junior Accountant",
        "title_ar": "محاسب مبتدئ",
        "description_en": "Bookkeeping support at a registered audit office. No upfront fees.",
        "description_ar": "دعم مسك الدفاتر في مكتب تدقيق مسجل. بلا رسوم مقدمة.",
        "organization": "Tigris Audit",
        "position": "accountant",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "offline",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Financial Accounting Fundamentals",
        "title_ar": "أساسيات المحاسبة المالية",
        "description_en": "Intro accounting course with quizzes and certificate option.",
        "description_ar": "دورة محاسبة تمهيدية مع اختبارات وخيار شهادة.",
        "organization": "Coursera",
        "position": "accountant",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/",
    },
    # Engineer
    {
        "title_en": "Junior Civil Engineer",
        "title_ar": "مهندس مدني مبتدئ",
        "description_en": "Site assistance for licensed contractor projects in Baghdad.",
        "description_ar": "مساعدة ميدانية لمشاريع مقاول مرخص في بغداد.",
        "organization": "Al-Mustansiriya Builders",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "offline",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Engineering Project Basics",
        "title_ar": "أساسيات المشاريع الهندسية",
        "description_en": "Online course covering planning and safety fundamentals.",
        "description_ar": "دورة أونلاين عن التخطيط وأساسيات السلامة.",
        "organization": "Coursera",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/",
    },
    # HR
    {
        "title_en": "HR Coordinator",
        "title_ar": "منسق موارد بشرية",
        "description_en": "Recruitment coordination for a telecom company careers portal.",
        "description_ar": "تنسيق التوظيف عبر بوابة وظائف لشركة اتصالات.",
        "organization": "Iraq Telecom Careers",
        "position": "hr",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "offline",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Human Resources Foundations",
        "title_ar": "أساسيات الموارد البشرية",
        "description_en": "Intro HR course covering hiring ethics and compliance.",
        "description_ar": "دورة موارد بشرية تمهيدية عن أخلاقيات التوظيف والامتثال.",
        "organization": "Coursera",
        "position": "hr",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/",
    },
    # Customer support
    {
        "title_en": "Customer Support Agent",
        "title_ar": "موظف دعم العملاء",
        "description_en": "Chat support for an e-commerce brand. Paid training week.",
        "description_ar": "دعم عبر الدردشة لعلامة تجارة إلكترونية. أسبوع تدريب مدفوع.",
        "organization": "Souq Support Hub",
        "position": "customer_support",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Customer Service Fundamentals",
        "title_ar": "أساسيات خدمة العملاء",
        "description_en": "Free course on communication and ticket handling.",
        "description_ar": "دورة مجانية عن التواصل وإدارة التذاكر.",
        "organization": "Coursera",
        "position": "customer_support",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/",
    },
    # Volunteer
    {
        "title_en": "Youth Digital Literacy Volunteer",
        "title_ar": "متطوع لنشر الثقافة الرقمية للشباب",
        "description_en": "Help teens spot online job scams in community workshops.",
        "description_ar": "مساعدة الشباب على كشف نصب الوظائف في ورش مجتمعية.",
        "organization": "UNESCO Youth Network",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "volunteer",
        "mode": "offline",
        "opportunity_type": "volunteer",
        "is_free": True,
        "is_volunteer": True,
        "source_url": "https://www.unesco.org/",
    },
    # Nurse
    {
        "title_en": "Clinic Nurse (Licensed)",
        "title_ar": "ممرض/ة عيادة (مرخص)",
        "description_en": "Outpatient clinic shift work. Valid nursing license required.",
        "description_ar": "مناوبات عيادة خارجية. يشترط ترخيص تمريض ساري.",
        "organization": "Al-Kindi Clinic",
        "position": "nurse",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "job",
        "mode": "offline",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.linkedin.com/jobs/",
    },
    {
        "title_en": "Nursing Continuing Education Intro",
        "title_ar": "مقدمة تعليم تمريض مستمر",
        "description_en": "Online continuing-education modules for nurses.",
        "description_ar": "وحدات تعليم مستمر أونلاين للممرضين.",
        "organization": "Coursera",
        "position": "nurse",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/",
    },
]
