from __future__ import annotations

"""Verified opportunity catalog — direct enrollment/listing URLs with search fallbacks."""

SEED_OPPORTUNITIES: list[dict] = [
    # --- Google / Coursera certificates (direct) ---
    {
        "seed_id": "course-google-data-analytics",
        "title_en": "Google Data Analytics Professional Certificate",
        "title_ar": "شهادة جوجل الاحترافية لتحليل البيانات",
        "description_en": "Direct Coursera enrollment for Google's data analytics certificate path.",
        "description_ar": "تسجيل مباشر في مسار شهادة جوجل لتحليل البيانات على Coursera.",
        "organization": "Google / Coursera",
        "position": "data",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/google-data-analytics",
    },
    {
        "seed_id": "course-google-it-support",
        "title_en": "Google IT Support Professional Certificate",
        "title_ar": "شهادة جوجل الاحترافية لدعم تقنية المعلومات",
        "description_en": "Hands-on IT support curriculum with direct Coursera enrollment.",
        "description_ar": "منهج عملي لدعم تقنية المعلومات مع تسجيل مباشر على Coursera.",
        "organization": "Google / Coursera",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/google-it-support",
    },
    {
        "seed_id": "course-google-project-management",
        "title_en": "Google Project Management Professional Certificate",
        "title_ar": "شهادة جوجل الاحترافية لإدارة المشاريع",
        "description_en": "Project management certificate with portfolio-ready projects.",
        "description_ar": "شهادة إدارة مشاريع مع مشاريع جاهزة للمحفظة.",
        "organization": "Google / Coursera",
        "position": "hr",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/google-project-management",
    },
    {
        "seed_id": "course-google-ux-design",
        "title_en": "Google UX Design Professional Certificate",
        "title_ar": "شهادة جوجل الاحترافية لتصميم تجربة المستخدم",
        "description_en": "UX research, wireframes, and Figma workflows — direct enrollment.",
        "description_ar": "بحث UX وإطارات وFigma — تسجيل مباشر.",
        "organization": "Google / Coursera",
        "position": "designer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/google-ux-design",
    },
    {
        "seed_id": "course-google-digital-marketing",
        "title_en": "Google Digital Marketing & E-commerce Certificate",
        "title_ar": "شهادة جوجل للتسويق الرقمي والتجارة الإلكترونية",
        "description_en": "SEO, ads, analytics, and e-commerce fundamentals.",
        "description_ar": "SEO وإعلانات وتحليلات وأساسيات التجارة الإلكترونية.",
        "organization": "Google / Coursera",
        "position": "marketing",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/google-digital-marketing-ecommerce",
    },
    {
        "seed_id": "course-google-cybersecurity",
        "title_en": "Google Cybersecurity Professional Certificate",
        "title_ar": "شهادة جوجل الاحترافية للأمن السيبراني",
        "description_en": "Security operations, SIEM, and incident response basics.",
        "description_ar": "عمليات أمنية وSIEM وأساسيات الاستجابة للحوادث.",
        "organization": "Google / Coursera",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/google-cybersecurity",
    },
    {
        "seed_id": "course-meta-frontend",
        "title_en": "Meta Front-End Developer Professional Certificate",
        "title_ar": "شهادة Meta الاحترافية لمطور الواجهات الأمامية",
        "description_en": "React, JavaScript, and front-end engineering path.",
        "description_ar": "React وJavaScript ومسار هندسة الواجهات الأمامية.",
        "organization": "Meta / Coursera",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/meta-front-end-developer",
    },
    {
        "seed_id": "course-ibm-data-science",
        "title_en": "IBM Data Science Professional Certificate",
        "title_ar": "شهادة IBM الاحترافية لعلوم البيانات",
        "description_en": "Python, SQL, visualization, and machine learning intro.",
        "description_ar": "Python وSQL وتصور بيانات ومقدمة تعلم آلي.",
        "organization": "IBM / Coursera",
        "position": "data",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/professional-certificates/ibm-data-science",
    },
    {
        "seed_id": "course-coursera-teaching",
        "title_en": "Foundations of Teaching for Learning",
        "title_ar": "أساسيات التعليم والتعلّم",
        "description_en": "Free Coursera course on lesson design and classroom practice.",
        "description_ar": "دورة Coursera مجانية عن تصميم الدروس وممارسة الصف.",
        "organization": "Coursera / Commonwealth Education Trust",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/learn/teach-learn",
    },
    {
        "seed_id": "course-coursera-accounting",
        "title_en": "Introduction to Financial Accounting",
        "title_ar": "مقدمة في المحاسبة المالية",
        "description_en": "Wharton accounting fundamentals with audit trail concepts.",
        "description_ar": "أساسيات محاسبة Wharton مع مفاهيم التدقيق.",
        "organization": "Coursera / Wharton",
        "position": "accountant",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/learn/wharton-accounting",
    },
    {
        "seed_id": "course-coursera-hr",
        "title_en": "Human Resources Management: HR for People Managers",
        "title_ar": "إدارة الموارد البشرية للمديرين",
        "description_en": "Hiring, performance, and compliance basics for HR coordinators.",
        "description_ar": "أساسيات التوظيف والأداء والامتثال لمنسقي HR.",
        "organization": "Coursera / University of Minnesota",
        "position": "hr",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/learn/human-resources",
    },
    {
        "seed_id": "course-coursera-customer-service",
        "title_en": "Customer Service Fundamentals",
        "title_ar": "أساسيات خدمة العملاء",
        "description_en": "Communication, empathy, and ticket handling for support roles.",
        "description_ar": "تواصل وتعاطف وإدارة تذاكر لأدوار الدعم.",
        "organization": "Coursera",
        "position": "customer_support",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/specializations/customer-service",
    },
    # --- freeCodeCamp (direct curriculum) ---
    {
        "seed_id": "course-fcc-responsive-web",
        "title_en": "freeCodeCamp Responsive Web Design",
        "title_ar": "تصميم الويب المتجاوب — freeCodeCamp",
        "description_en": "Free HTML/CSS certification with hands-on projects.",
        "description_ar": "شهادة HTML/CSS مجانية مع مشاريع عملية.",
        "organization": "freeCodeCamp",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.freecodecamp.org/learn/responsive-web-design-v9/",
    },
    {
        "seed_id": "course-fcc-javascript",
        "title_en": "freeCodeCamp JavaScript Algorithms",
        "title_ar": "خوارزميات JavaScript — freeCodeCamp",
        "description_en": "Core JavaScript and problem solving for web developers.",
        "description_ar": "JavaScript أساسية وحل مسائل لمطوري الويب.",
        "organization": "freeCodeCamp",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.freecodecamp.org/learn/javascript-v9/",
    },
    {
        "seed_id": "course-fcc-frontend-libs",
        "title_en": "freeCodeCamp Front-End Development Libraries",
        "title_ar": "مكتبات تطوير الواجهات — freeCodeCamp",
        "description_en": "React, Redux, and modern front-end tooling.",
        "description_ar": "React وRedux وأدوات الواجهات الحديثة.",
        "organization": "freeCodeCamp",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.freecodecamp.org/learn/front-end-development-libraries-v9/",
    },
    {
        "seed_id": "course-fcc-python",
        "title_en": "freeCodeCamp Scientific Computing with Python",
        "title_ar": "الحوسبة العلمية بـ Python — freeCodeCamp",
        "description_en": "Python fundamentals for data and automation tasks.",
        "description_ar": "أساسيات Python للبيانات والأتمتة.",
        "organization": "freeCodeCamp",
        "position": "data",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.freecodecamp.org/learn/python-v9/",
    },
    # --- CS50 ---
    {
        "seed_id": "course-cs50-harvard",
        "title_en": "CS50x — Introduction to Computer Science",
        "title_ar": "CS50x — مقدمة في علوم الحاسوب",
        "description_en": "Harvard's flagship CS intro — direct course page.",
        "description_ar": "مقدمة هارفارد الرئيسية في علوم الحاسوب — صفحة الكورس مباشرة.",
        "organization": "Harvard",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://cs50.harvard.edu/x/",
        "fallback_url": "https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science",
        "deadline": "2026-12-31",
    },
    {
        "seed_id": "course-cs50-edx",
        "title_en": "CS50 on edX (verified certificate path)",
        "title_ar": "CS50 على edX (مسار الشهادة الموثقة)",
        "description_en": "Official edX enrollment page for CS50x.",
        "description_ar": "صفحة التسجيل الرسمية على edX لـ CS50x.",
        "organization": "HarvardX / edX",
        "position": "developer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.edx.org/learn/computer-science/harvard-university-cs50-s-introduction-to-computer-science",
    },
    # --- Jobs (direct listing or filtered search + fallback) ---
    {
        "seed_id": "job-unicef-listing",
        "title_en": "UNICEF Open Vacancies",
        "title_ar": "وظائف يونيسف المفتوحة",
        "description_en": "Browse current UNICEF jobs including Iraq and remote roles.",
        "description_ar": "تصفح وظائف يونيسف الحالية بما فيها العراق والعمل عن بُعد.",
        "organization": "UNICEF",
        "position": "hr",
        "governorate": "baghdad",
        "city": "Global",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://jobs.unicef.org/en-us/listing/",
        "fallback_url": "https://www.unicef.org/careers",
        "deadline": "Rolling",
    },
    {
        "seed_id": "job-unesco-all",
        "title_en": "UNESCO All Job Openings",
        "title_ar": "جميع وظائف اليونسكو المفتوحة",
        "description_en": "Official UNESCO careers board with field and HQ posts.",
        "description_ar": "لوحة وظائف اليونسكو الرسمية للمقر والميدان.",
        "organization": "UNESCO",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Global",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://careers.unesco.org/go/All-jobs-openings/784002/",
        "fallback_url": "https://careers.unesco.org/",
        "deadline": "Rolling",
    },
    {
        "seed_id": "job-undp-vacancies",
        "title_en": "UNDP Current Vacancies",
        "title_ar": "الوظائف الحالية في برنامج الأمم المتحدة الإنمائي",
        "description_en": "UNDP jobs and consultancies — filter by Iraq or remote.",
        "description_ar": "وظائف UNDP واستشارات — فلترة حسب العراق أو عن بُعد.",
        "organization": "UNDP",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Global",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://jobs.undp.org/cj_view_jobs.cfm",
        "fallback_url": "https://www.undp.org/careers",
        "deadline": "Rolling",
    },
    {
        "seed_id": "job-un-careers",
        "title_en": "UN Careers Job Openings",
        "title_ar": "وظائف الأمم المتحدة",
        "description_en": "United Nations official careers portal for staff positions.",
        "description_ar": "بوابة الأمم المتحدة الرسمية للوظائف.",
        "organization": "United Nations",
        "position": "hr",
        "governorate": "baghdad",
        "city": "Global",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://careers.un.org/",
        "fallback_url": "https://careers.un.org/jobopening",
        "deadline": "Rolling",
    },
    {
        "seed_id": "job-who-careers",
        "title_en": "WHO Careers — Current Vacancies",
        "title_ar": "وظائف منظمة الصحة العالمية",
        "description_en": "Health sector roles including Iraq country office when posted.",
        "description_ar": "وظائف صحية بما فيها مكتب العراق عند الإعلان.",
        "organization": "WHO",
        "position": "doctor",
        "governorate": "baghdad",
        "city": "Global",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://careers.who.int/careersection/ex/jobsearch.ftl",
        "fallback_url": "https://www.who.int/careers",
        "deadline": "Rolling",
    },
    {
        "seed_id": "job-wfp-careers",
        "title_en": "WFP Careers Portal",
        "title_ar": "بوابة وظائف برنامج الأغذية العالمي",
        "description_en": "Logistics, programme, and IT roles across MENA region.",
        "description_ar": "وظائف لوجستية وبرامج وتقنية في المنطقة.",
        "organization": "WFP",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Global",
        "category": "job",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://careers.wfp.org/careersection/ex/jobsearch.ftl",
        "fallback_url": "https://www.wfp.org/jobs-and-careers",
        "deadline": "Rolling",
    },
    # --- Internships ---
    {
        "seed_id": "intern-unicef-programme",
        "title_en": "UNICEF Internship Programme",
        "title_ar": "برنامج تدريب يونيسف",
        "description_en": "How to apply and link to live internship vacancies.",
        "description_ar": "كيفية التقديم والانتقال للإعلانات المفتوحة.",
        "organization": "UNICEF",
        "position": "hr",
        "governorate": "baghdad",
        "city": "Global",
        "category": "internship",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.unicef.org/careers/internships",
        "fallback_url": "https://jobs.unicef.org/en-us/listing/?category=Internship",
        "deadline": "Rolling",
    },
    {
        "seed_id": "intern-unesco-board",
        "title_en": "UNESCO Internships & Volunteers",
        "title_ar": "تدريب وتطوع اليونسكو",
        "description_en": "Live internship listings at UNESCO HQ and field offices.",
        "description_ar": "إعلانات تدريب حية في المقر والمكاتب الميدانية.",
        "organization": "UNESCO",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Global",
        "category": "internship",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://careers.unesco.org/go/Internships-and-volunteers/783902/",
        "fallback_url": "https://careers.unesco.org/content/Internship-Programme/?locale=en_GB",
        "deadline": "Rolling",
    },
    {
        "seed_id": "intern-unesco-rules",
        "title_en": "UNESCO Internship Programme Guide",
        "title_ar": "دليل برنامج تدريب اليونسكو",
        "description_en": "Eligibility, duration, and application steps for UNESCO interns.",
        "description_ar": "الأهلية والمدة وخطوات التقديم لمتدربي اليونسكو.",
        "organization": "UNESCO",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Global",
        "category": "internship",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://careers.unesco.org/content/Internship-Programme/?locale=en_GB",
        "fallback_url": "https://careers.unesco.org/go/Internships-and-volunteers/783902/",
    },
    {
        "seed_id": "intern-undp-jobs",
        "title_en": "UNDP Internship Vacancies",
        "title_ar": "فرص تدريب UNDP",
        "description_en": "Filter UNDP jobs board for internship and trainee posts.",
        "description_ar": "فلترة لوحة UNDP لإعلانات التدريب.",
        "organization": "UNDP",
        "position": "data",
        "governorate": "baghdad",
        "city": "Global",
        "category": "internship",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://jobs.undp.org/cj_view_jobs.cfm",
        "fallback_url": "https://www.undp.org/careers/internships",
        "deadline": "Rolling",
    },
    {
        "seed_id": "intern-aiesec-search",
        "title_en": "AIESEC Global Internship Search",
        "title_ar": "بحث تدريب AIESEC العالمي",
        "description_en": "Youth leadership internships — filter Middle East & Africa.",
        "description_ar": "تدريب قيادة شبابية — فلترة الشرق الأوسط وأفريقيا.",
        "organization": "AIESEC",
        "position": "marketing",
        "governorate": "erbil",
        "city": "Global",
        "category": "internship",
        "mode": "online",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://aiesec.org/search",
        "fallback_url": "https://www.aiesec.org/",
        "deadline": "Rolling",
    },
    {
        "seed_id": "intern-iaea",
        "title_en": "IAEA Internship Programme",
        "title_ar": "برنامج تدريب الوكالة الدولية للطاقة الذرية",
        "description_en": "STEM internships at IAEA headquarters and labs.",
        "description_ar": "تدريب STEM في مقر الوكالة والمختبرات.",
        "organization": "IAEA",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Vienna",
        "category": "internship",
        "mode": "offline",
        "opportunity_type": "paid",
        "is_free": False,
        "is_volunteer": False,
        "source_url": "https://www.iaea.org/about/employment/internships",
        "fallback_url": "https://careers.iaea.org/",
        "deadline": "Rolling",
    },
    # --- Volunteer ---
    {
        "seed_id": "vol-unv-online",
        "title_en": "UN Online Volunteering",
        "title_ar": "التطوع الإلكتروني للأمم المتحدة",
        "description_en": "Remote volunteer tasks for youth worldwide including Iraq.",
        "description_ar": "مهام تطوع عن بُعد للشباب بما فيهم العراق.",
        "organization": "UN Volunteers",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Online",
        "category": "volunteer",
        "mode": "online",
        "opportunity_type": "volunteer",
        "is_free": True,
        "is_volunteer": True,
        "source_url": "https://www.unv.org/become-online-volunteer",
        "fallback_url": "https://app.unv.org/",
        "deadline": "Rolling",
    },
    {
        "seed_id": "vol-unv-portal",
        "title_en": "UNV Unified Volunteering Platform",
        "title_ar": "منصة التطوع الموحدة UNV",
        "description_en": "Search and apply to online and onsite UN volunteer roles.",
        "description_ar": "ابحث وقدّم على أدوار تطوع UN إلكترونية وميدانية.",
        "organization": "UN Volunteers",
        "position": "customer_support",
        "governorate": "baghdad",
        "city": "Online",
        "category": "volunteer",
        "mode": "online",
        "opportunity_type": "volunteer",
        "is_free": True,
        "is_volunteer": True,
        "source_url": "https://app.unv.org/",
        "fallback_url": "https://www.unv.org/",
        "deadline": "Rolling",
    },
    {
        "seed_id": "vol-unesco-youth",
        "title_en": "UNESCO Youth & Digital Literacy Volunteering",
        "title_ar": "تطوع شبابي وثقافة رقمية — اليونسكو",
        "description_en": "Community workshops to help teens spot online job scams.",
        "description_ar": "ورش مجتمعية لمساعدة المراهقين على كشف نصب الوظائف.",
        "organization": "UNESCO",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "volunteer",
        "mode": "offline",
        "opportunity_type": "volunteer",
        "is_free": True,
        "is_volunteer": True,
        "source_url": "https://careers.unesco.org/go/Internships-and-volunteers/783902/",
        "fallback_url": "https://www.unesco.org/en/youth",
        "deadline": "Rolling",
    },
    {
        "seed_id": "vol-redcross-iraq",
        "title_en": "Iraqi Red Crescent — Volunteer Registration",
        "title_ar": "تسجيل متطوعين — الهلال الأحمر العراقي",
        "description_en": "Local humanitarian volunteering across Iraqi governorates.",
        "description_ar": "تطوع إنساني محلي في محافظات العراق.",
        "organization": "Iraqi Red Crescent",
        "position": "nurse",
        "governorate": "baghdad",
        "city": "Baghdad",
        "category": "volunteer",
        "mode": "offline",
        "opportunity_type": "volunteer",
        "is_free": True,
        "is_volunteer": True,
        "source_url": "https://www.ifrc.org/national-societies/middle-east-and-north-africa/iraq",
        "fallback_url": "https://www.irck.org/",
        "deadline": "Rolling",
    },
    # --- Scholarships / fellowships ---
    {
        "seed_id": "schol-chevening-iraq",
        "title_en": "Chevening Scholarships — Iraq",
        "title_ar": "منح Chevening — العراق",
        "description_en": "UK master's scholarships for Iraqi professionals.",
        "description_ar": "منح ماجستير في بريطانيا للمهنيين العراقيين.",
        "organization": "Chevening / UK FCDO",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "UK",
        "category": "scholarship",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.chevening.org/scholarship/iraq/",
        "fallback_url": "https://www.chevening.org/apply/",
        "deadline": "Annual cycle",
    },
    {
        "seed_id": "schol-chevening-apply",
        "title_en": "Chevening Application Portal",
        "title_ar": "بوابة التقديم على Chevening",
        "description_en": "Direct application entry when the annual window is open.",
        "description_ar": "بوابة التقديم المباشرة عند فتح الدورة السنوية.",
        "organization": "Chevening",
        "position": "hr",
        "governorate": "baghdad",
        "city": "UK",
        "category": "scholarship",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.chevening.org/apply/",
        "fallback_url": "https://www.chevening.org/scholarship/iraq/",
        "deadline": "Annual cycle",
    },
    {
        "seed_id": "schol-erasmus-mundus",
        "title_en": "Erasmus Mundus Joint Masters Catalogue",
        "title_ar": "كتalog منح Erasmus Mundus للماجستير المشترك",
        "description_en": "EU-funded master's programmes with direct programme pages.",
        "description_ar": "برامج ماجستير ممولة من الاتحاد الأوروبي بصفحات مباشرة.",
        "organization": "European Commission",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Europe",
        "category": "scholarship",
        "mode": "offline",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.eacea.ec.europa.eu/scholarships/erasmus-mundus-catalogue_en",
        "fallback_url": "https://erasmus-plus.ec.europa.eu/opportunities",
        "deadline": "Oct–Jan cycles",
    },
    {
        "seed_id": "schol-daad-iraq",
        "title_en": "DAAD Iraq Scholarship Database",
        "title_ar": "قاعدة منح DAAD للعراق",
        "description_en": "Search funded study and research opportunities in Germany.",
        "description_ar": "ابحث عن فرص دراسة وبحث ممولة في ألمانيا.",
        "organization": "DAAD",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Germany",
        "category": "scholarship",
        "mode": "offline",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.daad-iraq.org/en/find-funding/scholarship-database/",
        "fallback_url": "https://www.daad.de/en/",
        "deadline": "Varies",
    },
    {
        "seed_id": "schol-fulbright-iraq",
        "title_en": "Fulbright Foreign Student Program — Iraq",
        "title_ar": "برنامج Fulbright للطلاب الأجانب — العراق",
        "description_en": "U.S. graduate study — embassy hub and application cycle.",
        "description_ar": "دراسات عليا في أمريكا — بوابة السفارة ودورة التقديم.",
        "organization": "IIE / U.S. Embassy Iraq",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "USA",
        "category": "scholarship",
        "mode": "offline",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://iq.usembassy.gov/professional-exchanges/",
        "fallback_url": "https://apply.iie.org/ffsp2027",
        "deadline": "Cycle-based",
    },
    {
        "seed_id": "schol-unesco-greatwall",
        "title_en": "UNESCO / China Great Wall Fellowships",
        "title_ar": "زمالات UNESCO / الصين Great Wall",
        "description_en": "Fellowships for advanced study in China — official UNESCO page.",
        "description_ar": "زمالات دراسات عليا في الصين — صفحة اليونسكو الرسمية.",
        "organization": "UNESCO",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "China",
        "category": "scholarship",
        "mode": "offline",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.unesco.org/en/fellowships/greatwall",
        "fallback_url": "https://www.unesco.org/en/fellowships",
        "deadline": "Annual cycle",
    },
    {
        "seed_id": "schol-unesco-hub",
        "title_en": "UNESCO Fellowships Hub",
        "title_ar": "بوابة زمالات اليونسكو",
        "description_en": "Index of UNESCO fellowship programmes worldwide.",
        "description_ar": "فهرس برامج زمالات اليونسكو حول العالم.",
        "organization": "UNESCO",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "Global",
        "category": "scholarship",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.unesco.org/en/fellowships",
        "deadline": "Rolling",
    },
    {
        "seed_id": "schol-educationusa",
        "title_en": "EducationUSA — Study in the U.S.",
        "title_ar": "EducationUSA — الدراسة في أمريكا",
        "description_en": "Advising and scholarship resources for Iraqi students.",
        "description_ar": "إرشاد وموارد منح للطلاب العراقيين.",
        "organization": "EducationUSA",
        "position": "teacher",
        "governorate": "baghdad",
        "city": "USA",
        "category": "scholarship",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://educationusa.state.gov/",
        "fallback_url": "https://iq.usembassy.gov/education-culture/",
        "deadline": "Rolling",
    },
    # --- Additional role-specific courses ---
    {
        "seed_id": "course-coursera-nursing",
        "title_en": "Vital Signs: Understanding What the Body Is Telling Us",
        "title_ar": "العلامات الحيوية: فهم ما يخبرنا به الجسم",
        "description_en": "Clinical basics for nursing and health support roles.",
        "description_ar": "أساسيات سريرية للتمريض والدعم الصحي.",
        "organization": "Coursera / University of Pennsylvania",
        "position": "nurse",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/learn/vital-signs",
    },
    {
        "seed_id": "course-coursera-engineering",
        "title_en": "Construction Project Management",
        "title_ar": "إدارة مشاريع الإنشاء",
        "description_en": "Planning, scheduling, and safety for civil engineers.",
        "description_ar": "تخطيط وجدولة وسلامة للمهندسين المدنيين.",
        "organization": "Coursera / Columbia University",
        "position": "engineer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/specializations/construction-project-management",
    },
    {
        "seed_id": "course-coursera-sales",
        "title_en": "Sales Training: Practical Sales Techniques",
        "title_ar": "تدريب المبيعات: تقنيات عملية",
        "description_en": "Prospecting, pitching, and closing for sales roles.",
        "description_ar": "استكشاف وعرض وإغلاق صفقات لأدوار المبيعات.",
        "organization": "Coursera",
        "position": "sales",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/learn/sales-training",
    },
    {
        "seed_id": "course-coursera-translator",
        "title_en": "Translation in Practice",
        "title_ar": "الترجمة في الممارسة",
        "description_en": "Professional translation workflows and quality checks.",
        "description_ar": "سير عمل ترجمة احترافية ومراجعة الجودة.",
        "organization": "Coursera",
        "position": "translator",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/learn/translation-in-practice",
    },
    {
        "seed_id": "course-coursera-photography",
        "title_en": "Photography Basics and Beyond",
        "title_ar": "أساسيات التصوير وما بعدها",
        "description_en": "Camera settings, composition, and editing fundamentals.",
        "description_ar": "إعدادات الكamera والتكوين وأساسيات التحرير.",
        "organization": "Coursera / Michigan State University",
        "position": "photographer",
        "governorate": "baghdad",
        "city": "Online",
        "category": "course",
        "mode": "online",
        "opportunity_type": "free",
        "is_free": True,
        "is_volunteer": False,
        "source_url": "https://www.coursera.org/specializations/photography-basics",
    },
]
